name: Docker Compose CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Start services
        run: |
          docker compose up -d
          docker compose ps

      # - name: Run tests
      #   run: |
      #     # Example: run tests inside a specific container
      #     docker-compose exec -T your_service_name ./run_tests.sh

      - name: Tear down services
        if: always()
        run: |
          docker-compose down
